TOKEN = 'YOUR_TOKEN_HERE'

PREFIX = '.'

HANDLERS = [
    'yui.handlers.age',
    'yui.handlers.animal',
    'yui.handlers.answer',
    'yui.handlers.aqi',
    'yui.handlers.aws',
    'yui.handlers.book',
    'yui.handlers.calc',
    'yui.handlers.closers.command',
    'yui.handlers.closers.crontab',
    'yui.handlers.core',
    'yui.handlers.dday',
    'yui.handlers.dic',
    'yui.handlers.dns',
    'yui.handlers.exchange',
    'yui.handlers.help',
    'yui.handlers.hi',
    'yui.handlers.loading',
    'yui.handlers.memo',
    'yui.handlers.nyaa',
    'yui.handlers.ping',
    'yui.handlers.pongdang',
    'yui.handlers.quit',
    'yui.handlers.ref',
    'yui.handlers.saomd',
    'yui.handlers.select',
    'yui.handlers.sub',
    'yui.handlers.subscribe',
    'yui.handlers.subway',
    'yui.handlers.gamble',
]

MODELS = [
    'yui.models',
]

OWNER = 'U11111111'

DATABASE_URL = 'postgresql://postgres:MYSECRET@db/dbname'
DATABASE_ECHO = false

NAVER_CLIENT_ID = 'NAVER_CLIENT_ID'
NAVER_CLIENT_SECRET = 'NAVER_CLIENT_SECRET'

GOOGLE_API_KEY = 'GOOGLE_API_KEY'

AQI_API_TOKEN = 'AQI_API_TOKEN'

WEBSOCKETDEBUGGERURL = 'http://headless_chrome:9222/json/version'

[CHANNELS]
general = '_general'
game = 'game'
game_and_test = ['game', 'test']
welcome = '_general'

[LOGGING]
version = 1
disable_existing_loggers = false

[LOGGING.formatters.brief]
format = '%(message)s'

[LOGGING.formatters.default]
format = '%(asctime)s %(levelname)s %(name)s %(message)s'
datefmt = '%Y-%m-%d %H:%M:%S'

[LOGGING.handlers.console]
class = 'logging.StreamHandler'
formatter = 'default'
level = 'DEBUG'
filters = []
stream = 'ext://sys.stdout'

[LOGGING.handlers.file]
class = 'logging.handlers.RotatingFileHandler'
formatter = 'default'
level = 'WARNING'
filename = 'log/warning.log'
maxBytes = 1024
backupCount = 3

[LOGGING.loggers.yui]
handlers = ['console', 'file']
propagate = true
level = 'DEBUG'
